#include "../include/termstylist.h"
#include <iostream>

int main() {
    std::cout << '\n';

    //attributes
    std::cout << termstylist::ATTRS_Bold << "Bold" << termstylist::RESET_Bold << " ";
    std::cout << termstylist::ATTRS_Dim << "Dim" << termstylist::RESET_Dim << " ";
    std::cout << termstylist::ATTRS_Underline << "Underline" << termstylist::RESET_Underline << " ";
    std::cout << termstylist::ATTRS_Reverse << "Reverse" << termstylist::RESET_Reverse << " ";

    std::cout << '\n' << '\n';

    //foreground colours (8 colours)
    std::cout << termstylist::FG_Default << "FG Default" << " ";
    std::cout << termstylist::FG_Black << "FG Black" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG_Red << "FG Red" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG_Green << "FG Green" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG_Yellow << "FG Yellow" << termstylist::FG_Default << '\n';
    std::cout << termstylist::FG_Blue << "FG Blue" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG_Magenta << "FG Magenta" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG_Cyan << "FG Cyan" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG_White << "FG White" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG_LightGrey << "FG Light Grey" << termstylist::FG_Default << '\n';
    std::cout << termstylist::FG_DarkGrey << "FG Dark Grey" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG_LightRed << "FG Light Red" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG_LightGreen << "FG Light Green" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG_LightYellow << "FG Light Yellow" << termstylist::FG_Default << '\n';
    std::cout << termstylist::FG_LightBlue << "FG Light Blue" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG_LightMagenta << "FG Light Magenta" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG_LightCyan << "FG Light Cyan" << termstylist::FG_Default << " ";

    std::cout << '\n' << '\n';

    //foreground colours (16 colours)
    std::cout << termstylist::FG_BoldBlack << "FG Bold Black" << termstylist::RESET_Default << " ";
    std::cout << termstylist::FG_BoldRed << "FG Bold Red" << termstylist::RESET_Default << " ";
    std::cout << termstylist::FG_BoldGreen << "FG Bold Green" << termstylist::RESET_Default << " ";
    std::cout << termstylist::FG_BoldYellow << "FG Bold Yellow" << termstylist::RESET_Default << '\n';
    std::cout << termstylist::FG_BoldBlue << "FG Bold Blue" << termstylist::RESET_Default << " ";
    std::cout << termstylist::FG_BoldMagenta << "FG Bold Magenta" << termstylist::RESET_Default << " ";
    std::cout << termstylist::FG_BoldCyan << "FG Bold Cyan" << termstylist::RESET_Default << " ";
    std::cout << termstylist::FG_BoldWhite << "FG Bold White" << termstylist::RESET_Default << '\n';
    std::cout << termstylist::FG_BoldLightGrey << "FG Bold Light Grey" << termstylist::RESET_Default << " ";
    std::cout << termstylist::FG_BoldDarkGrey << "FG Bold Dark Grey" << termstylist::RESET_Default << " ";
    std::cout << termstylist::FG_BoldLightRed << "FG Bold Light Red" << termstylist::RESET_Default << " ";
    std::cout << termstylist::FG_BoldLightGreen << "FG Bold Light Green" << termstylist::RESET_Default << '\n';
    std::cout << termstylist::FG_BoldLightYellow << "FG Bold Light Yellow" << termstylist::RESET_Default << " ";
    std::cout << termstylist::FG_BoldLightBlue << "FG Bold Light Blue" << termstylist::RESET_Default << " ";
    std::cout << termstylist::FG_BoldLightMagenta << "FG Bold Light Magenta" << termstylist::RESET_Default << " ";
    std::cout << termstylist::FG_BoldLightCyan << "FG Bold Light Cyan" << termstylist::RESET_Default << " ";
 
    std::cout << '\n' << '\n';

    //background colours (8 colours)
    std::cout << termstylist::BG_Default << "BG Default" << " ";
    std::cout << termstylist::BG_Black << "BG Black" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG_Red << "BG Red" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG_Green << "BG Green" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG_Yellow << "BG Yellow" << termstylist::BG_Default << '\n';
    std::cout << termstylist::BG_Blue << "BG Blue" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG_Magenta << "BG Magenta" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG_Cyan << "BG Cyan" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG_White << "BG White" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG_LightGrey << "BG Light Grey" << termstylist::BG_Default << '\n';
    std::cout << termstylist::BG_DarkGrey << "BG Dark Grey" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG_LightRed << "BG Light Red" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG_LightGreen << "BG Light Green" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG_LightYellow << "BG Light Yellow" << termstylist::BG_Default << '\n';
    std::cout << termstylist::BG_LightBlue << "BG Light Blue" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG_LightMagenta << "BG Light Magenta" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG_LightCyan << "BG Light Cyan" << termstylist::BG_Default << " ";
    
    std::cout << '\n' << '\n';

    //background colours (16 colours)
    std::cout << termstylist::BG_BoldBlack << "BG Bold Black" << termstylist::RESET_Default << " ";
    std::cout << termstylist::BG_BoldRed << "BG Bold Red" << termstylist::RESET_Default << " ";
    std::cout << termstylist::BG_BoldGreen << "BG Bold Green" << termstylist::RESET_Default << " ";
    std::cout << termstylist::BG_BoldYellow << "BG Bold Yellow" << termstylist::RESET_Default << " ";
    std::cout << termstylist::BG_BoldBlue << "BG Bold Blue" << termstylist::RESET_Default << '\n';
    std::cout << termstylist::BG_BoldMagenta << "BG Bold Magenta" << termstylist::RESET_Default << " ";
    std::cout << termstylist::BG_BoldCyan << "BG Bold Cyan" << termstylist::RESET_Default << " ";
    std::cout << termstylist::BG_BoldWhite << "BG Bold White" << termstylist::RESET_Default << " ";
    std::cout << termstylist::BG_BoldLightGrey << "BG Bold Light Grey" << termstylist::RESET_Default << " ";
    std::cout << termstylist::BG_BoldDarkGrey << "BG Bold Dark Grey" << termstylist::RESET_Default << '\n';
    std::cout << termstylist::BG_BoldLightRed << "BG Bold Light Red" << termstylist::RESET_Default << " ";
    std::cout << termstylist::BG_BoldLightGreen << "BG Bold Light Green" << termstylist::RESET_Default << " ";
    std::cout << termstylist::BG_BoldLightYellow << "BG Bold Light Yellow" << termstylist::RESET_Default << " ";
    std::cout << termstylist::BG_BoldLightBlue << "BG Bold Light Blue" << termstylist::RESET_Default << '\n';
    std::cout << termstylist::BG_BoldLightMagenta << "BG Bold Light Magenta" << termstylist::RESET_Default << " ";
    std::cout << termstylist::BG_BoldLightCyan << "BG Bold Light Cyan" << termstylist::RESET_Default << " ";

    std::cout << '\n' << '\n';

    //foreground colours (256 colours)
    std::cout << termstylist::FG256_0 << "0" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_1 << "1" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_2 << "2" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_3 << "3" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_4 << "4" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_5 << "5" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_6 << "6" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_7 << "7" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_8 << "8" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_9 << "9" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_10 << "10" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_11 << "11" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_12 << "12" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_13 << "13" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_14 << "14" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_15 << "15" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_16 << "16" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_17 << "17" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_18 << "18" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_19 << "19" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_20 << "20" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_21 << "21" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_22 << "22" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_23 << "23" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_24 << "24" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_25 << "25" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_26 << "26" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_27 << "27" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_28 << "28" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_29 << "29" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_30 << "30" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_31 << "31" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_32 << "32" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_33 << "33" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_34 << "34" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_35 << "35" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_36 << "36" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_37 << "37" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_38 << "38" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_39 << "39" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_40 << "40" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_41 << "41" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_42 << "42" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_43 << "43" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_44 << "44" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_45 << "45" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_46 << "46" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_47 << "47" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_48 << "48" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_49 << "49" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_50 << "50" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_51 << "51" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_52 << "52" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_53 << "53" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_54 << "54" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_55 << "55" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_56 << "56" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_57 << "57" << termstylist::FG_Default << " "; 
    std::cout << termstylist::FG256_58 << "58" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_59 << "59" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_60 << "60" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_61 << "61" << termstylist::FG_Default << " "; 
    std::cout << termstylist::FG256_62 << "62" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_63 << "63" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_64 << "64" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_65 << "65" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_66 << "66" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_67 << "67" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_68 << "68" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_69 << "69" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_70 << "70" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_71 << "71" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_72 << "72" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_73 << "73" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_74 << "74" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_75 << "75" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_76 << "76" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_77 << "77" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_78 << "78" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_79 << "79" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_80 << "80" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_81 << "81" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_82 << "82" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_83 << "83" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_84 << "84" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_85 << "85" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_86 << "86" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_87 << "87" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_88 << "88" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_89 << "89" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_90 << "90" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_91 << "91" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_92 << "92" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_93 << "93" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_94 << "94" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_95 << "95" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_96 << "96" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_97 << "97" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_98 << "98" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_99 << "99" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_100 << "100" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_101 << "101" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_102 << "102" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_103 << "103" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_104 << "104" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_105 << "105" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_106 << "106" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_107 << "107" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_108 << "108" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_109 << "109" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_110 << "110" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_111 << "111" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_112 << "112" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_113 << "113" << termstylist::FG_Default << " "; 
    std::cout << termstylist::FG256_114 << "114" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_115 << "115" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_116 << "116" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_117 << "117" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_118 << "118" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_119 << "119" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_120 << "120" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_121 << "121" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_122 << "122" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_123 << "123" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_124 << "124" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_125 << "125" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_126 << "126" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_127 << "127" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_128 << "128" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_129 << "129" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_130 << "130" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_131 << "131" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_132 << "132" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_133 << "133" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_134 << "134" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_135 << "135" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_136 << "136" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_137 << "137" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_138 << "138" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_139 << "139" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_140 << "140" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_141 << "141" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_142 << "142" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_143 << "143" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_144 << "144" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_145 << "145" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_146 << "146" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_147 << "147" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_148 << "148" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_149 << "149" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_150 << "150" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_151 << "151" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_152 << "152" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_153 << "153" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_154 << "154" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_155 << "155" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_156 << "156" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_157 << "157" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_158 << "158" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_159 << "159" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_160 << "160" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_161 << "161" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_162 << "162" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_163 << "163" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_164 << "164" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_165 << "165" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_166 << "166" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_167 << "167" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_168 << "168" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_169 << "169" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_170 << "170" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_171 << "171" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_172 << "172" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_173 << "173" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_174 << "174" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_175 << "175" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_176 << "176" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_177 << "177" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_178 << "178" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_179 << "179" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_180 << "180" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_181 << "181" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_182 << "182" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_183 << "183" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_184 << "184" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_185 << "185" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_186 << "186" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_187 << "187" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_188 << "188" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_189 << "189" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_190 << "190" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_191 << "191" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_192 << "192" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_193 << "193" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_194 << "194" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_195 << "195" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_196 << "196" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_197 << "197" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_198 << "198" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_199 << "199" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_200 << "200" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_201 << "201" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_202 << "202" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_203 << "203" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_204 << "204" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_205 << "205" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_206 << "206" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_207 << "207" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_208 << "208" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_209 << "209" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_210 << "210" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_211 << "211" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_212 << "212" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_213 << "213" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_214 << "214" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_215 << "215" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_216 << "216" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_217 << "217" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_218 << "218" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_219 << "219" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_220 << "220" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_221 << "221" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_222 << "222" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_223 << "223" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_224 << "224" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_225 << "225" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_226 << "226" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_227 << "227" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_228 << "228" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_229 << "229" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_230 << "230" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_231 << "231" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_232 << "232" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_233 << "233" << termstylist::FG_Default << " "; 
    std::cout << termstylist::FG256_234 << "234" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_235 << "235" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_236 << "236" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_237 << "237" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_238 << "238" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_239 << "239" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_240 << "240" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_241 << "241" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_242 << "242" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_243 << "243" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_244 << "244" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_245 << "245" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_246 << "246" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_247 << "247" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_248 << "248" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_249 << "249" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_250 << "250" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_251 << "251" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_252 << "252" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_253 << "253" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_254 << "254" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_255 << "255" << termstylist::FG_Default << " ";
    std::cout << termstylist::FG256_256 << "256" << termstylist::FG_Default << " ";

    std::cout << '\n' << '\n';

    //background colours (256 colours)
    std::cout << termstylist::BG256_0 << "0" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_1 << "1" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_2 << "2" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_3 << "3" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_4 << "4" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_5 << "5" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_6 << "6" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_7 << "7" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_8 << "8" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_9 << "9" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_10 << "10" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_11 << "11" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_12 << "12" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_13 << "13" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_14 << "14" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_15 << "15" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_16 << "16" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_17 << "17" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_18 << "18" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_19 << "19" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_20 << "20" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_21 << "21" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_22 << "22" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_23 << "23" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_24 << "24" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_25 << "25" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_26 << "26" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_27 << "27" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_28 << "28" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_29 << "29" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_30 << "30" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_31 << "31" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_32 << "32" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_33 << "33" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_34 << "34" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_35 << "35" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_36 << "36" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_37 << "37" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_38 << "38" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_39 << "39" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_40 << "40" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_41 << "41" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_42 << "42" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_43 << "43" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_44 << "44" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_45 << "45" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_46 << "46" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_47 << "47" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_48 << "48" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_49 << "49" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_50 << "50" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_51 << "51" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_52 << "52" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_53 << "53" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_54 << "54" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_55 << "55" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_56 << "56" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_57 << "57" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_58 << "58" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_59 << "59" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_60 << "60" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_61 << "61" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_62 << "62" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_63 << "63" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_64 << "64" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_65 << "65" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_66 << "66" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_67 << "67" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_68 << "68" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_69 << "69" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_70 << "70" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_71 << "71" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_72 << "72" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_73 << "73" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_74 << "74" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_75 << "75" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_76 << "76" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_77 << "77" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_78 << "78" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_79 << "79" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_80 << "80" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_81 << "81" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_82 << "82" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_83 << "83" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_84 << "84" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_85 << "85" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_86 << "86" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_87 << "87" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_88 << "88" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_89 << "89" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_90 << "90" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_91 << "91" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_92 << "92" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_93 << "93" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_94 << "94" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_95 << "95" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_96 << "96" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_97 << "97" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_98 << "98" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_99 << "99" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_100 << "100" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_101 << "101" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_102 << "102" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_103 << "103" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_104 << "104" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_105 << "105" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_106 << "106" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_107 << "107" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_108 << "108" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_109 << "109" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_110 << "110" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_111 << "111" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_112 << "112" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_113 << "113" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_114 << "114" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_115 << "115" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_116 << "116" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_117 << "117" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_118 << "118" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_119 << "119" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_120 << "120" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_121 << "121" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_122 << "122" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_123 << "123" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_124 << "124" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_125 << "125" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_126 << "126" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_127 << "127" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_128 << "128" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_129 << "129" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_130 << "130" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_131 << "131" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_132 << "132" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_133 << "133" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_134 << "134" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_135 << "135" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_136 << "136" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_137 << "137" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_138 << "138" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_139 << "139" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_140 << "140" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_141 << "141" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_142 << "142" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_143 << "143" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_144 << "144" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_145 << "145" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_146 << "146" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_147 << "147" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_148 << "148" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_149 << "149" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_150 << "150" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_151 << "151" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_152 << "152" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_153 << "153" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_154 << "154" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_155 << "155" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_156 << "156" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_157 << "157" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_158 << "158" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_159 << "159" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_160 << "160" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_161 << "161" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_162 << "162" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_163 << "163" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_164 << "164" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_165 << "165" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_166 << "166" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_167 << "167" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_168 << "168" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_169 << "169" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_170 << "170" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_171 << "171" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_172 << "172" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_173 << "173" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_174 << "174" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_175 << "175" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_176 << "176" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_177 << "177" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_178 << "178" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_179 << "179" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_180 << "180" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_181 << "181" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_182 << "182" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_183 << "183" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_184 << "184" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_185 << "185" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_186 << "186" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_187 << "187" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_188 << "188" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_189 << "189" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_190 << "190" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_191 << "191" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_192 << "192" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_193 << "193" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_194 << "194" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_195 << "195" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_196 << "196" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_197 << "197" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_198 << "198" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_199 << "199" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_200 << "200" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_201 << "201" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_202 << "202" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_203 << "203" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_204 << "204" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_205 << "205" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_206 << "206" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_207 << "207" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_208 << "208" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_209 << "209" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_210 << "210" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_211 << "211" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_212 << "212" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_213 << "213" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_214 << "214" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_215 << "215" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_216 << "216" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_217 << "217" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_218 << "218" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_219 << "219" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_220 << "220" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_221 << "221" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_222 << "222" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_223 << "223" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_224 << "224" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_225 << "225" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_226 << "226" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_227 << "227" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_228 << "228" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_229 << "229" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_230 << "230" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_231 << "231" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_232 << "232" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_233 << "233" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_234 << "234" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_235 << "235" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_236 << "236" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_237 << "237" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_238 << "238" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_239 << "239" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_240 << "240" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_241 << "241" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_242 << "242" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_243 << "243" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_244 << "244" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_245 << "245" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_246 << "246" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_247 << "247" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_248 << "248" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_249 << "249" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_250 << "250" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_251 << "251" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_252 << "252" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_253 << "253" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_254 << "254" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_255 << "255" << termstylist::BG_Default << " ";
    std::cout << termstylist::BG256_256 << "256" << termstylist::BG_Default << " ";

    std::cout << '\n' << '\n';

    return 0;
}
